spring:
  application:
    name: policyservice

server:
  port: 8001
---

---
# dev
spring:
    profiles:
        active: dev

    # mongo
    mongodb:
      uri: mongodb+srv://d_mongo_kit:TempPwd@dmongokit.ailxasx.mongodb.net/d_Mongo_Kit

---
# qa
spring:
    profiles:
        active: qa

    # mongo
    mongodb:
      uri: mongodb+srv://d_mongo_kit:TempPwd@dmongokit.ailxasx.mongodb.net/d_Mongo_Kit

---
# prod
spring:
    profiles:
        active: prod

    mongodb:
        uri: mongodb+srv://d_mongo_kit:TempPwd@dmongokit.ailxasx.mongodb.net/d_Mongo_Kit

