spring:
  application:
    name: policyservice

server:
  port: 8001
---
# dev
spring:
    profiles:
        activate:
          on-profile: dev

  # mongo
    mongodb:
      uri: mongodb+srv://d_mongo_kit:${Mongo_Pwd}@policymanagementsystem.oxemfpl.mongodb.net/PolicyManagementSystem

---
# qa
spring:
    profiles:
      activate:
        on-profile: qa

    # mongo
    mongodb:
      uri: mongodb+srv://d_mongo_kit:${Mongo_Pwd}@policymanagementsystem.oxemfpl.mongodb.net/PolicyManagementSystemQA

---
# prod
spring:
    profiles:
        activate:
          on-profile: prod

    mongodb:
      uri: mongodb+srv://d_mongo_kit:${Mongo_Pwd}@policymanagementsystem.oxemfpl.mongodb.net/PolicyManagementSystemProd

