coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        if_not_found: failure

    patch:
      default:
        target: 80%
        threshold: 0%
        if_not_found: failure