spring:
  application:
    name: governanceservice

server:
  port: 8003

---

spring:
  config:
    activate:
      on-profile: dev

  mongodb:
    uri: mongodb+srv://d_mongo_kit:TempPwd@policymanagementsystem.oxemfpl.mongodb.net/PolicyManagementSystem?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: governance-dev-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

---

spring:
  config:
    activate:
      on-profile: qa

  mongodb:
    uri: mongodb+srv://d_mongo_kit:${Mongo_Pwd}@policymanagementsystem.oxemfpl.mongodb.net/PolicyManagementSystemQA?authSource=admin

---

spring:
  config:
    activate:
      on-profile: prod

  mongodb:
    uri: mongodb+srv://d_mongo_kit:${Mongo_Pwd}@policymanagementsystem.oxemfpl.mongodb.net/PolicyManagementSystemProd?authSource=admin