package com.clientdata.schemas.enums;

public enum Category {
    FINANCIAL_REGULATIONS,
    DATA_PROTECTION,
    ENVIRONMENTAL_REGULATIONS,
    HEALTH_AND_SAFETY,
    EMPLOYMENT_LAW,
    CONSUMER_PROTECTION,
    INTELLECTUAL_PROPERTY,
    ANTI_MONEY_LAUNDERING,
    TAXATION,
    EXPORT_CONTROL,
    INDUSTRY_SPECIFIC_REGULATIONS,
    GENERAL_COMPLIANCE,
}
