package com.clientdata.schemas.enums;

public enum PolicyStatus {
    DRAFT,
    UPLOADED,
    UNDER_REVIEW,
    VALIDATED,
    ARCHIVED,
    REJECTED,
    SENT_FOR_SILVER_PROCESSING,
    SILVER_PROCESSING_COMPLETED,
    SENT_FOR_GOLD_PROCESSING,
    GOLD_PROCESSING_COMPLETED,
    SAVED,
    SENT_VIA_KAFKA_STREAM_TO_GOLD,
    SENT_VIA_KAFKA_STREAM_TO_PLATINUM,
    APPROVER_ACCEPTANCE_RECEIVED,
    APPROVER_ACCEPTANCE_REJECTED,
    APPROVER_ACCEPTANCE_COMPLETED,
    RECEIVED_AT_PLATINUM,
    SAVED_AT_PLATINUM
}
